name: build

on:
  push:
    branches:
      - master
      - release/*

jobs:
  Deploy:
    name: Build gatsby page
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn install

      - name: Build gatsby
        run: yarn build --log-pages
        env:
          CI: true

      - name: Firebase Tools
        run: sudo npm install -g firebase-tools

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_USEFUL }}'
          channelId: live
          projectId: useful
