name: build

on:
  push:
    branches:
      - master
      - release/*

jobs:
  Deploy:
    name: Build gatsby page
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      # See: https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install

      - name: Build gatsby
        run: yarn build --log-pages
        env:
          CI: true

      - name: Firebase Tools
        run: sudo yarn global add firebase-tools

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_USEFUL }}'
          channelId: live
          projectId: useful
